apiVersion: v2
type: application
name: mdai-hub
version: "0.9.0-dev"
description: MDAI Hub helm chart
appVersion: "0.9.0-dev"
dependencies:
  - name: nats
    version: ~1.3.9
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: opentelemetry-operator
    version: ~0.93
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
  - name: kube-prometheus-stack
    alias: kubeprometheusstack
    version: ~77.6
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeprometheusstack.enabled
  - name: metrics-server
    version: ~3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
  - name: valkey
    version: ~2.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
  - name: mdai-operator
    version: 0.2.1
    repository: oci://ghcr.io/decisiveai
    condition: mdai-operator.enabled
  - name: mdai-gateway
    version: 0.1.0
    repository: oci://ghcr.io/decisiveai
    condition: mdai-gateway.enabled
  - name: mdai-event-hub
    repository: oci://ghcr.io/decisiveai
    version: 0.1.0
    condition: mdai-event-hub.enabled
  - name: mdai-s3-logs-reader
    version: 0.0.6
    repository: oci://ghcr.io/decisiveai
    condition: mdai-s3-logs-reader.enabled
