apiVersion: v2
type: application
name: mdai-hub
kubeVersion: ">=1.24.0"
version: "0.8.5-dev"
description: MDAI Hub helm chart
appVersion: "0.8.5-dev"
dependencies:
  - name: nats
    version: ~1.3.9
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: opentelemetry-operator
    version: ~0.71.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
  - name: kube-prometheus-stack
    alias: kubeprometheusstack
    version: ~65.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeprometheusstack.enabled
  - name: metrics-server
    version: ~3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
  - name: valkey
    version: ~2.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
  - name: mdai-operator
    version: 0.1.22
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-operator.enabled
  - name: mdai-gateway
    version: 0.0.15
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-gateway.enabled
  - name: mdai-event-hub
    repository: oci://ghcr.io/decisiveai
    version: 0.0.9
    condition: mdai-event-hub.enabled
  - name: mdai-s3-logs-reader
    version: 0.0.5
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-s3-logs-reader.enabled
