apiVersion: v2
type: application
name: mdai-hub
version: "0.8.0-dev"
description: MDAI Hub helm chart
appVersion: "0.8.0-dev"
dependencies:
  - name: rabbitmq
    version: ~16.0.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled
  - name: opentelemetry-operator
    version: ~0.71.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
  - name: kube-prometheus-stack
    alias: kubeprometheusstack
    version: ~65.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeprometheusstack.enabled
  - name: metrics-server
    version: ~3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server
    condition: metrics-server.enabled
  - name: valkey
    version: ~2.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
  - name: mdai-operator
    version: 0.1.19
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-operator.enabled
  - name: mdai-gateway
    version: 0.0.14
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-gateway.enabled
  - name: mdai-event-hub
    version: 0.0.6
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-event-hub.enabled
  - name: mdai-s3-logs-reader
    version: 0.0.4
    repository: https://decisiveai.github.io/mdai-helm-charts
    condition: mdai-s3-logs-reader.enabled
