{
 "title": "MDAI Data Management Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Ingress Volume by service",
   "type": "timeseries",
   "description": "Bytes received/sent per service",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(\n  sum by (service_name, data_type) (\n    label_replace(\n      {__name__=~\"mdai_(log|metric|span)_bytes_received_total\"},\n      \"data_type\",\n      \"$1\",\n      \"__name__\",\n      \"mdai_(log|metric|span)_bytes_received_total\"\n    )\n  )[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Egress Volume by service",
   "type": "timeseries",
   "description": "Bytes received/sent per service",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(\n  sum by (service_name, data_type) (\n    label_replace(\n      {__name__=~\"mdai_(log|metric|span)_bytes_sent_total\"},\n      \"data_type\",\n      \"$1\",\n      \"__name__\",\n      \"mdai_(log|metric|span)_bytes_sent_total\"\n    )\n  )[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Volume per Telemetry Type (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(\n  sum by (data_type) (\n    label_replace(\n      {__name__=~\"mdai_(log|metric|span)_bytes_received_total\"},\n      \"data_type\",\n      \"$1\",\n      \"__name__\",\n      \"mdai_(log|metric|span)_bytes_received_total\"\n    )\n  )[1h:]\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(\n  sum by (data_type) (\n    label_replace(\n      {__name__=~\"mdai_(log|metric|span)_bytes_sent_total\"},\n      \"data_type\",\n      \"$1\",\n      \"__name__\",\n      \"mdai_(log|metric|span)_bytes_sent_total\"\n    )\n  )[1h:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active data filtering alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(alertname) (ALERTS{alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Filter Rules",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Log Volume Filtered Services",
   "type": "timeseries",
   "description": "Bytes received/sent per service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(\n  sum by (service_name) (\n    mdai_log_bytes_received_total and ignoring(alertname, alertstate, time, __name__, instance, job, severity) ALERTS{alertstate=\"firing\"}\n  )[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress Log Volume Filtered Services",
   "type": "timeseries",
   "description": "Bytes received/sent per service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(\n  sum by (service_name) (\n    mdai_log_bytes_sent_total and ignoring(alertname, alertstate, time, __name__, instance, job, severity) ALERTS{alertstate=\"firing\"}\n  )[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Volume Filtered Services",
   "type": "timeseries",
   "description": "Bytes received/sent per service",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(\n  sum by (service_name) (\n    mdai_log_bytes_received_total and ignoring(alertname, alertstate, time, __name__, instance, job, severity) ALERTS{alertstate=\"firing\"}\n  )[5m:]\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(\n  sum by (service_name) (\n    mdai_log_bytes_sent_total and ignoring(alertname, alertstate, time, __name__, instance, job, severity) ALERTS{alertstate=\"firing\"}\n  )[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress/Ingress Bytes Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(\n  sum by (service_name) (\n    mdai_log_bytes_sent_total and ignoring(alertname, alertstate, time, __name__, instance, job, severity) ALERTS{alertstate=\"firing\"}\n  )[5m:]\n) / increase(\n  sum by (service_name) (\n    mdai_log_bytes_received_total and ignoring(alertname, alertstate, time, __name__, instance, job, severity) ALERTS{alertstate=\"firing\"}\n  )[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}