{
 "title": "MDAI Logs (Valkey Streams + Prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "query": "MDAI_ERR_RATE hub 20", "streamingInterval": 20000, "type": "cli" }
   ]
  },
  {
   "title": "Errors rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (logstream, loglevel) (rate(mdai_own_logs_total{loglevel=\"Error\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fatal errors rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (logstream, loglevel) (rate(mdai_own_logs_total{loglevel=\"Fatal\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hub Fatal Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "command": "xrange",
     "end": "+",
     "keyName": "hub",
     "start": "-",
     "type": "command"
    }
   ]
  },
  {
   "title": "Audit Fatal Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "command": "xrange",
     "end": "+",
     "keyName": "audit",
     "start": "-",
     "type": "command"
    }
   ]
  },
  {
   "title": "Collector Fatal Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "command": "xrange",
     "end": "+",
     "keyName": "collector",
     "start": "-",
     "type": "command"
    }
   ]
  }
 ]
}