apiVersion: v1
kind: Service
metadata:
  name: nats-metrics
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
spec:
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ include "nats.instance" . }}
    app.kubernetes.io/component: nats
  ports:
    - name: metrics
      port: 7777
      targetPort: 7777