---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-cleanup-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-cleanup-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-cleanup-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: pvc-cleanup-sa
roleRef:
  kind: Role
  name: pvc-cleanup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Namespace }}-pvc-cleanup
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      serviceAccountName: pvc-cleanup-sa
      restartPolicy: Never
      containers:
      - name: delete-pvc
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Deleting PVCs for release {{ .Release.Name }}..."
            kubectl delete pvc -l "app.kubernetes.io/instance={{ .Release.Name }}" --namespace {{ .Release.Namespace }}
